### ISSUE TITLE
spanish verb data seems corrupt for the second person form

### ISSUE THREAD

**Issue by fschwiet** [ian-hamlin/verb-data#1]
As an example, in abrir.json, there is an entry:

```
{"form": "s2", "group": "indicative/present", "group_sort": 4, "sort": 1, "value": "abresabr\u00eds (t\u00fa) -  (vos)"}
```

It looks like the formal and informal values have been merged.

**Comment by fschwiet** [comment]
It looks like the data in proto form has the same issue.

**Comment by ian-hamlin** [comment]
Thanks for picking that up, I'll take a look and get the data refreshed.

**Comment by ian-hamlin** [comment]
FYI, I've found the problem and should be able to get the data fixed in the next few days.

**Comment by fschwiet** [comment]
That's good to hear, thank you.

I was curious if you had planned to add english verb conjugations at some point?

Thanks for making this stuff available.

**Comment by ian-hamlin** [comment]
English is less interesting too me, as it's my native language, so I tend to favour the ones that seem more exotic.

I'm not against the idea however, but I doubt I will find the time/motivation to do it in the near/medium term :(

**Comment by ian-hamlin** [comment]
The new data is ready, I just need to do some spot checks and if that goes OK I will format it for upload.

**Comment by ian-hamlin** [comment]
Spanish JSON and Proto have been updated.  Thanks again for flagging the issue.

**Comment by fschwiet** [comment]
It looks like

https://github.com/ian-hamlin/verb-data/blob/master/json/spanish/content/a/abrir.json

still has

{"form": "s2", "group": "indicative/present", "group_sort": 4, "sort": 1, "value": "abres (t\u00fa) - abr\u00eds (vos)"}

**Comment by ian-hamlin** [comment]
Hmm not sure what happened there, I'll take another look

**Comment by fschwiet** [comment]
Thank you.  Consider writing the json with whitespace/newlines on the next update, it would make git's diffs and change history more useful.

**Comment by fschwiet** [comment]
I had worked around this by splitting the values on ' ' and taking the part I need.

I wanted to ask what sources you are using for scraping this data?  I had been using http://conjugation.sensagant.com, which is pretty good (does english as well as spanish, verb conjugation as well as noun pluralization/gender matching) but it stopped working maybe a week ago.

**Comment by ian-hamlin** [comment]
Sorry for the delay, I've been swamped with other work, but this is still on my radar, happy to hear you found a work around in the short term.

All the data is taken from https://en.wiktionary.org/wiki/Wiktionary:Main_Page as I only deal in verbs I just start at the verb pages for each target language and go from there.

**Comment by fschwiet** [comment]
Don't apologize please, I appreciate the work you have and its not like I'm paying.

I did want to note some other issues I've seen.

-  Some fields have comma separated values (see escribir, whose past participle has an archaic form included as well).  Also see ciar which has alternate forms for vosotros for some things (just adding an accent).

- musir.json has musirse as its infinitive, which I'd expect in musirse.json but not musir.json.  Musir may not even be a real verb, I haven't found it via google.

**Comment by ian-hamlin** [comment]
All the data looks better now, for the verbs mentioned in this ticket.  I can not verify is Musir is real or not, but it does appear on the source site (https://en.wiktionary.org/?curid=5536613#Spanish) so I will leave it in.
