### ISSUE TITLE
New web app based on your data.

### ISSUE THREAD

**Issue by bhtsmeets** [ian-hamlin/verb-data#4]
Hi Ian,

I hope you are doing well.
As I am learning Clojure and Italian, I thought I could combine the two. I created a web-app in Clojure that uses verb-data. It is a small app that can be used to exercise your favorite verbs and tenses. As far as I know (though I am probably wrong) this is not yet available on Internet. I could not have made it without verb.data. Thanks a lot.
Depending on the state of the universe, I might or might not improve the app in the future, e.g. anki-like repeated training/daily challenge, other grammar exercises, persistent local or remote storage, internationalisation of the interface, create native mobile versions.
Let me know if you have any concerns or thoughts about the app.
I almost forgot: lalingua.primamodi.com
Take care

**Comment by ian-hamlin** [comment]
Hi,

I think it's fantastic, really nice to see someone using the data, and this
seems like a useful tool to practice verbs.

I hope your Italian learning goes well!

Thanks
Ian
